title: "Sakshi Sharma"
email: "imsakshivk@gmail.com"
description: >-
  Academic Portfolio – Assistant Professor, Ph.D. Scholar, Blockchain & Cybersecurity Researcher.
baseurl: "" # Leave empty if the site is at the root (https://username.github.io)
url: "https://your-username.github.io" # Change to your GitHub Pages URL
theme: minima

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Optional: navigation
header_pages:
  - index.md
  - projects.md
  - publications.md
